[package]
name = "segmentlist"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = "0.4.6"
num-traits = "0.2.19"
pyo3 = { version = "0.24.1", features = ["extension-module", "num-bigint"] }
