name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies with uv
        run: uv sync --dev

      - name: Run ruff lints
        run: uv run ruff check .

      - name: Run ruff formatting
        run: uv run ruff format --check .

      - name: Run tests
        run: uv run pytest -v test_segment_list.py
